version: '3'
services:
  app:
    build: .
    ports:
     - "3000:3000"
    volumes:
    - ./:/usr/src/app
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bootcamp
